apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: porkbun-secret
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: porkbun-secret
    creationPolicy: Owner
  data:
    - secretKey: PORKBUN_API_KEY
      remoteRef:
        key: porkbun-api-key
    - secretKey: PORKBUN_SECRET_API_KEY
      remoteRef:
        key: porkbun-secret-api-key
