apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: porkbun-webhook
  namespace: cert-manager
spec:
  interval: 1h
  url: oci://ghcr.io/noetarbouriech/webhook-porkbun/charts/porkbun-webhook
  ref:
    tag: 0.0.0-858c3b4
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: porkbun-webhook
  namespace: cert-manager
spec:
  interval: 1h
  releaseName: porkbun-webhook
  chartRef:
    kind: OCIRepository
    name: porkbun-webhook
  values:
    groupName: acme.noe-t.dev
    image:
      repository: ghcr.io/noetarbouriech/webhook-porkbun
      tag: latest
      pullPolicy: Always
