apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: porkbun-webhook
spec:
  interval: 1h
  type: oci
  url: oci://ghcr.io/noetarbouriech/webhook-porkbun/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: porkbun-webhook
spec:
  interval: 1h
  releaseName: porkbun-webhook
  chart:
    spec:
      chart: porkbun-webhook
      sourceRef:
        kind: HelmRepository
        name: porkbun-webhook
        namespace: flux-system
      interval: 1h
