apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: porkbun-webhook
spec:
  interval: 1h
  url: oci://ghcr.io/noetarbouriech/webhook-porkbun/charts/porkbun-webhook
  ref:
    digest: sha256:e3c6443f808b121eedd34d8a894312276d49bb9829148cbc44b5c91a755d3a66
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: porkbun-webhook
spec:
  interval: 1h
  releaseName: porkbun-webhook
  chartRef:
    kind: OCIRepository
    name: porkbun-webhook
  values:
    groupName: acme.noe-t.dev
    image:
      repository: ghcr.io/noetarbouriech/webhook-porkbun
      tag: latest
      pullPolicy: Always
