apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-logs-collector
spec:
  interval: 15m
  ref:
    tag: 0.2.15
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-logs-collector
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs-collector
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-logs-collector
  interval: 1h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    remoteWrite:
      - url: http://victoria-logs-single-server:9428
        headers:
          VL-Ignore-Fields:
            - kubernetes.namespace_labels*
            - kubernetes.pod_labels*
