apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: bitwarden-selfsigned
  namespace: external-secrets
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-sdk-server-tls
  namespace: external-secrets
spec:
  secretName: bitwarden-sdk-server-tls
  isCA: true
  subject:
    organizations:
      - external-secrets-bitwarden
  commonName: bitwarden-sdk-server
  dnsNames:
    - bitwarden-sdk-server.external-secrets.svc.cluster.local
    - bitwarden-sdk-server.external-secrets.svc
    - localhost
  ipAddresses:
    - 127.0.0.1
  issuerRef:
    name: bitwarden-selfsigned
    kind: Issuer
