apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      caProvider:
        type: Secret
        namespace: external-secrets
        name: bitwarden-sdk-server-tls
        key: ca.crt
      organizationID: 01af6a1d-eda8-433f-adb0-b369010cb3a5
      projectID: acc89a8e-9b95-4c50-9c32-b426011506ca
      auth:
        secretRef:
          credentials:
            name: bitwarden-access-token
            key: token
            namespace: external-secrets
