apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: crafty
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: crafty
  validation:
    hostname: mc.home.noe-t.dev
    wellKnownCACertificates: System
