apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: crafty-panel
spec:
  secretName: crafty-panel-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
    - mc.home.noe-t.dev
