apiVersion: v1
kind: ConfigMap
metadata:
  name: victorialogs-datasource
  namespace: observability
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: VictoriaLogs
        type: victoriametrics-logs-datasource
        access: proxy
        url: http://victoria-logs-single-server:9428
